#MYSQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_db?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: jeongwon.park.0314@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true